### ISSUE TITLE
**[ipv]** EIP 712 签名内加入更多相关信息：fee, input-sum

### ISSUE THREAD

**Issue by stwith** [lay2dev/ckb.pw#8]
当前签名的 EIP 712 内仅包含交易哈希和 outputs，为了方便用户了解交易实际情况，建议在字段中加入 input-sum，了解本次交易输入总和；增加 fee 字段，了解本次交易所需手续费。

**Comment by zhixianio** [comment]
这个 issue 之前我加过了，我的意思是加一个在钱包 ui 里显示更多信息的 issue，用于化解用户对总 outputs + fee = balance 的预期
